### ISSUE TITLE
Backend returns HTTP code 504

### ISSUE THREAD

**Issue by marcnause** [fossasia/loklak_wok_android#7]
I have noticed that most requests to the backend (http://loklag.org) return HTTP code 504 (gateway timeout).

I changed the logging in Harvester.java (line 276) to output a stacktrace to the log and I get this a lot:

D/PushThread: failed synchronous push to backend, attempt 0
    java.io.IOException: Server returned non-OK status: 504
        at org.loklak.tools.NetworkIO.pushString(Unknown Source)
        at org.loklak.tools.JsonIO.pushJson(Unknown Source)
        at org.loklak.client.PushClient.push(Unknown Source)
        at org.loklak.android.wok.Harvester$PushThread.doInBackground(Harvester.java:263)
        at org.loklak.android.wok.Harvester$PushThread.doInBackground(Harvester.java:244)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)

**Comment by sudheesh001** [comment]
@Low012 Would it be possible to provide the query URL that's being requested which is returning a 504 ?

**Comment by marcnause** [comment]
I have recorded a whole session using [Charles](https://www.charlesproxy.com/). If you don't happen to coincidentally own a license, you can download a trial version to look at the file (unzip attached file and open via File -> Import).

If just the failed request and the response is enough info for you, I have also attached them in plain text. Please note that it worked fine 25 times before I got the error. Yesterday the situation was different and most of my requests failed.

I think the issue should have been created in [loklak_server](https://github.com/loklak/loklak_server/) instead of here. My bad. :-\

[session.zip](https://github.com/loklak/loklak_wok_android/files/303349/session.zip)
[request.txt](https://github.com/loklak/loklak_wok_android/files/303352/request.txt)
[response.txt](https://github.com/loklak/loklak_wok_android/files/303351/response.txt)
